# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: GC Digital Research Bootcamp
description: GC Digital Research Bootcamp
url: gcdigitalfellows.github.io
author:
  name: GC Digital Fellows
  email: gc.digitalfellows@gmail.com
  uri: http://digitalfellows.commons.gc.cuny.edu
  bio: GC Digital Fellows
  twitter: Digital_Fellows
  github: http://github.com/GCDigitalFellows

# source: ./
destination: _site
# baseurl: /gcdrb
exclude:
  - '*.sh'
  - CNAME
  - bower_components
  - node_modules
  - '.*'

# _config.stage.yml overwrites these options when you run locally
future: false
limit_posts: 10 # Only make the last 10 posts so generating isn't slow
show_drafts: false

#required by github-pages
lsi: false # Disables the more accurate related posts
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

# Permalink structure and pagination options
# permalink: pretty
# paginate: 10
# paginate_path: 'page:num'
# excerpt_separator: '<!--more-->'

gems:
  - jekyll-paginate
  # - jekyll-coffeescript # uncomment this to enable coffeescript
